language: ruby
rvm:
  - 2.2

env:
  global:
    - "FTP_USER=troeste-teddys-aachen.de"
    - secure: "ES+9OXVnxp1TkBq3/28t4XaNCg6esA10Cot0dsDZdGMbtmuB59onf6GQOrHIf3gQLwsT9eepQ7V79Pj9XQnEjDeCjgMGgwECJbqNMKx+g8Vjpy27Vol6H7UuMyuTxjWmE5oMyQjxdlYmQlXeMV+6XyW7ZrK6URAaMLVu0DhlmnG5rl+GC8IQYpZdmfURN7auDdU9pKGaszMy56VyujNZo5HAXcRQEw0zngnUZA8anFgBb6QRZWfnG0RDlcpuArogahBhu/dnuNx0bPulkYN+Q+jAWQFjNARmaNnQM9R/VKt2oNWSjmX/NJv/XG7M08wKRHDt7RXQ0VLhMzsp2t7bMp7DTWTlvAdc0oqi0FktaGERSd+uJjDMQfnkmut1LAd2YsL+AgbD894aCoHPkczCwSqM70YZGsIsYRbqWOh0cRq73CnB0NaEJPbmj0kVPUTbWNyht7LQxIKKTH4eYLft/F869gkCCTsMNYjvPDO5E5x1DGMQQAz0t36/YYSiJKLrqjVbelD1hgchSv3+AwY9bh0QB03wQ52P1RBNBOyTzbu+4KXzPMQAqyWwU89ocEsV9lpcuMnbTQSOo7V89bT/KmwtQzHhegAYuJMV1CDyhcmWOmnanG7DceF6tKrEzrKiPwsiSk0KEK5KIfgiXsmwCUopicTwgq7pd6HaQvZUY6w="

branches:
  only:
    - master

install:
  - sudo apt-get update -qq
  - sudo apt-get install -y wput lftp
  - gem install github-pages

before_script: chmod +x ./_travis_scripts/empty_ftp.sh

script:
  - jekyll build --destination _site --trace
  - jekyll doctor
  - ./_travis_scripts/empty_ftp.sh $FTP_USER $FTP_PASSWORD

after_success:
  - cd _site
  - wput −−binary −−reupload −−dont−continue ./* ftp://$FTP_USER:$FTP_PASSWORD@ftp.strato.de/
