name: Teddys für Kinder in Not Aachen e.V.
safe: false
encoding: utf-8
markdown: kramdown
permalink: /posts/:title/
timezone: DE
emoji_dir: img/emoji
exclude: [Gemfile, Gemfile.lock, vendor]
gems: 
  - github-pages
  - emoji
